import { useEffect, useState } from "react";

const sections = [
  { id: "introduction", title: "Introduction" },
  { id: "how-it-works", title: "How It Works" },
  { id: "features", title: "Core Features" },
  { id: "workflow", title: "Typical Workflow" },
  { id: "safety", title: "Safety & Trust" },
  { id: "privacy", title: "Privacy & Data" },
  { id: "best-practices", title: "Best Practices" },
  { id: "faq", title: "FAQ" },
  { id: "getting-started", title: "Getting Started" },
];

const Documentation = () => {
  const [activeSection, setActiveSection] = useState("introduction");

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) setActiveSection(entry.target.id);
        });
      },
      { rootMargin: "-20% 0px -75% 0px" },
    );

    sections.forEach(({ id }) => {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, []);

  const scrollTo = (id: string) => {
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  return (
    <main className="min-h-screen bg-ld-neutral text-ld-on-surface">
      <div className="relative overflow-hidden pb-20 pt-32">
        <div className="mx-auto max-w-[1200px] px-6">
          <p className="section-label">Documentation</p>
          <h1 className="text-section-title">Refract</h1>
          <p className="text-body mt-4 max-w-[560px]">
            <strong className="text-ld-on-surface">
              Transform AI-generated code into maintainable, production-ready software.
            </strong>
          </p>
          <p className="text-body mt-3 max-w-[560px]">
            Refract is a code analysis and refactoring pipeline that bridges the gap between rapid AI-assisted prototyping and production-grade software quality. It analyzes codebases generated by tools like Lovable, Bolt, and Cursor, identifies structural issues, and provides actionable suggestions to eliminate comprehension debt.
          </p>
        </div>
      </div>

      <div className="border-t border-ld-border">
        <div className="mx-auto flex max-w-[1200px] px-6">
          <aside className="w-[220px] shrink-0 border-r border-ld-border py-12 pr-8">
            <nav className="sticky top-24">
              {sections.map((s) => (
                <button
                  key={s.id}
                  onClick={() => scrollTo(s.id)}
                  className={`nav-link mb-1 block w-full border-l-2 py-1.5 pl-3 text-left text-label-md transition-colors ${
                    activeSection === s.id
                      ? "border-ld-primary text-ld-on-surface"
                      : "border-transparent"
                  }`}
                >
                  {s.title}
                </button>
              ))}
            </nav>
          </aside>

          <div className="prose-docs min-w-0 max-w-[720px] flex-1 py-12 pl-12">
            <section id="introduction">
              <h2>Introduction</h2>
              <p className="mt-4">
                AI coding tools have made it trivially fast to generate functional code. But speed comes at a cost: AI-generated codebases accumulate "comprehension debt" — code that works but is difficult to understand, maintain, or extend. Modules grow oversized, types devolve to <code>any</code>, dependencies tangle into cycles, and documentation falls behind.
              </p>
              <p className="mt-3">
                Refract solves this. It is an AST-powered analysis engine that inspects your codebase, detects patterns of poor maintainability, and surfaces prioritized, actionable refactoring suggestions. For Pro and Team users, it can automate the entire refactoring workflow — generating pull requests with documented changes, updated documentation, and clean code structure — all while preserving the original behavior.
              </p>
            </section>

            <section id="how-it-works">
              <h2>How It Works</h2>
              <ol className="mt-12 list-none border-t border-ld-border p-0">
                {[
                  { n: "01", title: "Connect", body: "Link a GitHub or GitLab repository and select a branch to analyze." },
                  { n: "02", title: "Parse", body: "Refract clones or fetches the repository contents and parses every file into an Abstract Syntax Tree (AST) using Babel." },
                  { n: "03", title: "Analyze", body: "A suite of detectors walks the AST looking for specific issues: any type usage, oversized components, dead state, circular dependencies, missing error boundaries, and more." },
                  { n: "04", title: "Suggest", body: "Each issue is enriched with impact, effort, blast radius, and a suggested fix. Results are presented in a prioritized list with before/after code previews." },
                  { n: "05", title: "Refactor", body: "Users review suggestions individually or in batch. Pro/Team users can auto-generate a pull request with all accepted changes applied." },
                  { n: "06", title: "Document", body: "Refract can generate or update README files, API docs, and architecture overviews automatically." },
                ].map((s) => (
                  <li
                    key={s.n}
                    className="grid grid-cols-[56px_1fr] gap-6 border-b border-ld-border py-6"
                  >
                    <span className="font-mono text-[22px] text-ld-muted/50">{s.n}</span>
                    <div>
                      <h3 className="border-0 p-0 text-headline-sm">{s.title}</h3>
                      <p className="mt-2">{s.body}</p>
                    </div>
                  </li>
                ))}
              </ol>
              <p className="mt-6">
                The engine runs entirely in Web Workers for performance, with all parsing, detection, and enrichment happening client-side for privacy and speed.
              </p>
            </section>

            <section id="features">
              <h2>Core Features</h2>
              <div className="mt-10 flex flex-col gap-12">
                <div>
                  <h3>Code Analysis Engine</h3>
                  <ul className="list-disc">
                    <li><strong>AST-based Parsing</strong> — Uses <code>@babel/parser</code> with full TypeScript, JSX, and modern ECMAScript support.</li>
                    <li><strong>Detector Suite</strong> — 15+ built-in detectors covering: any-type usage, oversized components, dead state, missing documentation, console.log leaks, and more.</li>
                    <li><strong>Cross-file Analysis</strong> — Detects circular dependencies and duplicate logic across file boundaries.</li>
                  </ul>
                </div>
                <div>
                  <h3>Issue System</h3>
                  <ul className="list-disc">
                    <li><strong>Prioritization</strong> — Each issue is scored by a formula: <code>priority = (impact × 10 + blastRadius) / effort</code></li>
                    <li><strong>Categories</strong> — Issues are classified into 15 distinct categories with consistent IDs and metadata.</li>
                    <li><strong>Patches</strong> — Each issue carries a before/after patch for direct application.</li>
                  </ul>
                </div>
                <div>
                  <h3>Auto-Refract (Pro/Team)</h3>
                  <ul className="list-disc">
                    <li>Direct pull request generation with documented changes</li>
                    <li>Automatic changelog creation</li>
                    <li>Batch processing of multiple suggestions</li>
                  </ul>
                </div>
                <div>
                  <h3>Documentation Generation</h3>
                  <ul className="list-disc">
                    <li>Automatic README creation and updates</li>
                    <li>Function and module-level documentation</li>
                    <li>Architecture overview diagrams</li>
                  </ul>
                </div>
              </div>
            </section>

            <section id="workflow">
              <h2>Typical Workflow</h2>
              <ol className="list-decimal">
                <li><strong>Sign in</strong> via GitHub or GitLab OAuth.</li>
                <li><strong>Select a repository</strong> from your account and choose a branch.</li>
                <li><strong>Run analysis</strong> — Refract scans every file, runs all detectors, and builds the import map.</li>
                <li><strong>Review results</strong> on the Project View page.</li>
                <li><strong>Accept or reject</strong> individual suggestions.</li>
                <li><strong>Apply changes</strong> — Free users copy patches manually. Pro/Team users click "Generate PR".</li>
                <li><strong>Generate documentation</strong> — One-click README, API docs, or architecture docs.</li>
              </ol>
            </section>

            <section id="safety">
              <h2>Safety &amp; Trust</h2>
              <p className="mt-4">
                Refract is designed as a read-first, write-never-by-default system:
              </p>
              <ul className="list-disc">
                <li><strong>Analysis is read-only.</strong> The engine never modifies your repository without explicit user action.</li>
                <li><strong>Pull requests, not direct pushes.</strong> When applying changes, Refract creates a PR that you review and merge.</li>
                <li><strong>Suggestions are deterministic.</strong> Every detector produces the same result for the same input.</li>
                <li><strong>Sandboxed execution.</strong> Analysis runs in isolated Web Workers with no access to the DOM or network.</li>
              </ul>
            </section>

            <section id="privacy">
              <h2>Privacy &amp; Data</h2>
              <ul className="list-disc">
                <li><strong>Your code stays on your machine.</strong> All parsing, analysis, and issue generation happens client-side.</li>
                <li><strong>Repository metadata only.</strong> Only repository metadata is fetched — file contents remain local during analysis.</li>
                <li><strong>No code logging.</strong> We never log, store, or transmit your source code.</li>
                <li><strong>AI features are opt-in.</strong> If using AI-assisted suggestion generation, context is sent with your explicit consent.</li>
              </ul>
            </section>

            <section id="best-practices">
              <h2>Best Practices</h2>
              <ul className="list-disc">
                <li><strong>Run analysis early.</strong> Connect your repository as soon as you have a working prototype.</li>
                <li><strong>Focus on High priority issues first.</strong> The priority score accounts for both impact and blast radius.</li>
                <li><strong>Batch related suggestions.</strong> Accepting multiple suggestions in a single PR reduces review overhead.</li>
                <li><strong>Re-analyze after refactoring.</strong> Run a fresh analysis after applying changes to verify improvements.</li>
              </ul>
            </section>

            <section id="faq">
              <h2>FAQ</h2>
              <div className="mt-10 flex flex-col gap-8">
                {[
                  { q: "What is \"comprehension debt\"?", a: "Comprehension debt is the gap between code that works and code that is understood. AI-generated code is particularly prone to this because it optimizes for correctness over readability." },
                  { q: "Does Refract modify my code without permission?", a: "No. Analysis is always read-only. Any modification goes through a pull request workflow that you explicitly initiate and review." },
                  { q: "Can I use Refract with JavaScript projects?", a: "Yes. Refract supports TypeScript and JavaScript files (.ts, .tsx, .js, .jsx) via Babel's TypeScript plugin." },
                  { q: "How long does analysis take?", a: "Typical repositories (under 10,000 files) complete in under 5 minutes. Incremental re-analysis takes under 30 seconds." },
                  { q: "Does Refract work with monorepos?", a: "Yes. Refract treats the repository as a flat file system for import resolution. Monorepo structures with relative imports work correctly." },
                  { q: "Is Refract open source?", a: "Refract is proprietary software. A free tier is available for individual developers. Pro and Team plans unlock automated refactoring and team collaboration." },
                ].map((f) => (
                  <div key={f.q}>
                    <h3 className="border-0 p-0 text-headline-sm">{f.q}</h3>
                    <p className="mt-2">{f.a}</p>
                  </div>
                ))}
              </div>
            </section>

            <section id="getting-started" className="!mb-0">
              <h2>Getting Started</h2>
              <div className="mt-8">
                <h3 className="border-0 p-0 text-headline-sm">Prerequisites</h3>
                <ul className="list-disc">
                  <li>A GitHub or GitLab account with repositories you want to analyze</li>
                  <li>A modern web browser (Chrome, Firefox, Safari, or Edge)</li>
                </ul>
              </div>
              <div className="mt-8">
                <h3 className="border-0 p-0 text-headline-sm">Quick Start</h3>
                <ol className="list-decimal">
                  <li><strong>Visit the app</strong> and sign in via GitHub or GitLab OAuth.</li>
                  <li><strong>Connect a repository</strong> from your account and choose a branch.</li>
                  <li><strong>Run your first analysis</strong> — starts automatically after connecting.</li>
                  <li><strong>Review your results</strong> — health score, issues, and suggestions.</li>
                  <li><strong>Accept a suggestion</strong> — click to see the before/after diff.</li>
                  <li><strong>Generate a PR (Pro/Team)</strong> — create a pull request with all accepted changes.</li>
                </ol>
              </div>
            </section>
          </div>
        </div>
      </div>
    </main>
  );
};

export default Documentation;
