import { useEffect, useState } from "react";
import Navbar from "@/components/site/Navbar";
import Footer from "@/components/site/Footer";

const sections = [
  { id: "introduction", title: "Introduction" },
  { id: "how-it-works", title: "How It Works" },
  { id: "features", title: "Core Features" },
  { id: "workflow", title: "Typical Workflow" },
  { id: "safety", title: "Safety & Trust" },
  { id: "privacy", title: "Privacy & Data" },
  { id: "best-practices", title: "Best Practices" },
  { id: "faq", title: "FAQ" },
  { id: "getting-started", title: "Getting Started" },
];

const Documentation = () => {
  const [activeSection, setActiveSection] = useState("introduction");

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) setActiveSection(entry.target.id);
        });
      },
      { rootMargin: "-20% 0px -75% 0px" }
    );

    sections.forEach(({ id }) => {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, []);

  const scrollTo = (id: string) => {
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  return (
    <main className="page-enter" style={{ minHeight: "100vh", backgroundColor: "var(--surface-base)", color: "var(--text-primary)" }}>
      <Navbar />

      {/* Hero */}
      <div style={{ paddingTop: 128, paddingBottom: 80, backgroundColor: "var(--surface-base)", position: "relative", overflow: "hidden" }}>
        <div style={{ maxWidth: 1200, margin: "0 auto", padding: "0 24px" }}>
          <p style={{ fontSize: 12, fontWeight: 500, color: "rgba(255,255,255,0.4)", textTransform: "uppercase", letterSpacing: "0.1em" }}>Documentation</p>
          <h1 style={{ fontSize: 40, fontWeight: 700, color: "var(--text-primary)", marginTop: 16 }}>Refract</h1>
          <p style={{ marginTop: 16, maxWidth: 560, fontSize: 16, color: "var(--text-secondary)", lineHeight: 1.65 }}>
            <strong>Transform AI-generated code into maintainable, production-ready software.</strong>
          </p>
          <p style={{ marginTop: 12, maxWidth: 560, fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.65 }}>
            Refract is a code analysis and refactoring pipeline that bridges the gap between rapid AI-assisted prototyping and production-grade software quality. It analyzes codebases generated by tools like Lovable, Bolt, and Cursor, identifies structural issues, and provides actionable suggestions to eliminate comprehension debt.
          </p>
        </div>
      </div>

      {/* Content */}
      <div style={{ borderTop: "1px solid var(--border-subtle)" }}>
        <div style={{ maxWidth: 1200, margin: "0 auto", padding: "0 24px", display: "flex" }}>
          {/* Sidebar */}
          <aside style={{ width: 220, flexShrink: 0, padding: "48px 32px 48px 0", borderRight: "1px solid var(--border-subtle)" }}>
            <nav style={{ position: "sticky", top: 96 }}>
              {sections.map((s) => (
                <button
                  key={s.id}
                  onClick={() => scrollTo(s.id)}
                  style={{
                    display: "block", width: "100%", textAlign: "left", padding: "6px 12px", fontSize: 14,
                    background: "none", border: "none", borderLeft: activeSection === s.id ? "2px solid var(--text-primary)" : "2px solid transparent",
                    color: activeSection === s.id ? "var(--text-primary)" : "rgba(255,255,255,0.4)",
                    fontWeight: activeSection === s.id ? 600 : 400,
                    cursor: "pointer", transition: "color 0.15s ease",
                  }}
                >
                  {s.title}
                </button>
              ))}
            </nav>
          </aside>

          {/* Main content */}
          <div style={{ flex: 1, minWidth: 0, padding: "48px 0 48px 48px", maxWidth: 720 }}>

            {/* Introduction */}
            <section id="introduction" style={{ scrollMarginTop: 96, marginBottom: 80 }}>
              <h2 style={{ fontSize: 28, fontWeight: 700, color: "var(--text-primary)" }}>Introduction</h2>

              <p style={{ marginTop: 16, fontSize: 16, color: "var(--text-secondary)", lineHeight: 1.65 }}>
                AI coding tools have made it trivially fast to generate functional code. But speed comes at a cost: AI-generated codebases accumulate "comprehension debt" — code that works but is difficult to understand, maintain, or extend. Modules grow oversized, types devolve to <code>any</code>, dependencies tangle into cycles, and documentation falls behind.
              </p>

              <p style={{ marginTop: 12, fontSize: 16, color: "var(--text-secondary)", lineHeight: 1.65 }}>
                Refract solves this. It is an AST-powered analysis engine that inspects your codebase, detects patterns of poor maintainability, and surfaces prioritized, actionable refactoring suggestions. For Pro and Team users, it can automate the entire refactoring workflow — generating pull requests with documented changes, updated documentation, and clean code structure — all while preserving the original behavior.
              </p>
            </section>

            {/* How It Works */}
            <section id="how-it-works" style={{ scrollMarginTop: 96, marginBottom: 80, borderTop: "1px solid var(--border-subtle)", paddingTop: 64 }}>
              <h2 style={{ fontSize: 28, fontWeight: 700, color: "var(--text-primary)" }}>How It Works</h2>

              <ol style={{ marginTop: 48, display: "flex", flexDirection: "column", borderTop: "1px solid var(--border-subtle)", listStyle: "none", padding: 0 }}>
                {[
                  { n: "01", title: "Connect", body: "Link a GitHub or GitLab repository and select a branch to analyze." },
                  { n: "02", title: "Parse", body: "Refract clones or fetches the repository contents and parses every file into an Abstract Syntax Tree (AST) using Babel." },
                  { n: "03", title: "Analyze", body: "A suite of detectors walks the AST looking for specific issues: any type usage, oversized components, dead state, circular dependencies, missing error boundaries, and more." },
                  { n: "04", title: "Suggest", body: "Each issue is enriched with impact, effort, blast radius, and a suggested fix. Results are presented in a prioritized list with before/after code previews." },
                  { n: "05", title: "Refactor", body: "Users review suggestions individually or in batch. Pro/Team users can auto-generate a pull request with all accepted changes applied." },
                  { n: "06", title: "Document", body: "Refract can generate or update README files, API docs, and architecture overviews automatically." },
                ].map((s) => (
                  <li
                    key={s.n}
                    style={{ display: "grid", gridTemplateColumns: "56px 1fr", gap: 24, padding: "24px 0", borderBottom: "1px solid var(--border-subtle)", transition: "background 0.12s" }}
                  >
                     <span style={{ fontSize: 22, color: "rgba(255,255,255,0.3)", fontFamily: "'JetBrains Mono', monospace" }}>{s.n}</span>
                    <div>
                      <h3 style={{ fontSize: 18, fontWeight: 600, color: "var(--text-primary)" }}>{s.title}</h3>
                       <p style={{ marginTop: 8, fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.65 }}>{s.body}</p>
                    </div>
                  </li>
                ))}
              </ol>

              <p style={{ marginTop: 24, fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.65 }}>
                The engine runs entirely in Web Workers for performance, with all parsing, detection, and enrichment happening client-side for privacy and speed.
              </p>
            </section>

            {/* Core Features */}
            <section id="features" style={{ scrollMarginTop: 96, marginBottom: 80, borderTop: "1px solid var(--border-subtle)", paddingTop: 64 }}>
              <h2 style={{ fontSize: 28, fontWeight: 700, color: "var(--text-primary)" }}>Core Features</h2>

              <div style={{ marginTop: 40, display: "flex", flexDirection: "column", gap: 48 }}>
                <div>
                  <h3 style={{ fontSize: 20, fontWeight: 600, color: "var(--text-primary)", borderBottom: "1px solid var(--border-subtle)", paddingBottom: 8, marginBottom: 16 }}>Code Analysis Engine</h3>
                  <ul style={{ marginTop: 16, display: "flex", flexDirection: "column", gap: 12, fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.65, listStyleType: "disc", paddingLeft: 20 }}>
                    <li><strong>AST-based Parsing</strong> — Uses <code>@babel/parser</code> with full TypeScript, JSX, and modern ECMAScript support.</li>
                    <li><strong>Detector Suite</strong> — 15+ built-in detectors covering: any-type usage, oversized components, dead state, missing documentation, console.log leaks, and more.</li>
                    <li><strong>Cross-file Analysis</strong> — Detects circular dependencies and duplicate logic across file boundaries.</li>
                  </ul>
                </div>

                <div>
                  <h3 style={{ fontSize: 20, fontWeight: 600, color: "var(--text-primary)", borderBottom: "1px solid var(--border-subtle)", paddingBottom: 8, marginBottom: 16 }}>Issue System</h3>
                  <ul style={{ marginTop: 16, display: "flex", flexDirection: "column", gap: 12, fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.65, listStyleType: "disc", paddingLeft: 20 }}>
                    <li><strong>Prioritization</strong> — Each issue is scored by a formula: <code>priority = (impact × 10 + blastRadius) / effort</code></li>
                    <li><strong>Categories</strong> — Issues are classified into 15 distinct categories with consistent IDs and metadata.</li>
                    <li><strong>Patches</strong> — Each issue carries a before/after patch for direct application.</li>
                  </ul>
                </div>

                <div>
                  <h3 style={{ fontSize: 20, fontWeight: 600, color: "var(--text-primary)", borderBottom: "1px solid var(--border-subtle)", paddingBottom: 8, marginBottom: 16 }}>Auto-Refract (Pro/Team)</h3>
                  <ul style={{ marginTop: 16, display: "flex", flexDirection: "column", gap: 12, fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.65, listStyleType: "disc", paddingLeft: 20 }}>
                    <li>Direct pull request generation with documented changes</li>
                    <li>Automatic changelog creation</li>
                    <li>Batch processing of multiple suggestions</li>
                  </ul>
                </div>

                <div>
                  <h3 style={{ fontSize: 20, fontWeight: 600, color: "var(--text-primary)", borderBottom: "1px solid var(--border-subtle)", paddingBottom: 8, marginBottom: 16 }}>Documentation Generation</h3>
                  <ul style={{ marginTop: 16, display: "flex", flexDirection: "column", gap: 12, fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.65, listStyleType: "disc", paddingLeft: 20 }}>
                    <li>Automatic README creation and updates</li>
                    <li>Function and module-level documentation</li>
                    <li>Architecture overview diagrams</li>
                  </ul>
                </div>
              </div>
            </section>

            {/* Typical Workflow */}
            <section id="workflow" style={{ scrollMarginTop: 96, marginBottom: 80, borderTop: "1px solid var(--border-subtle)", paddingTop: 64 }}>
              <h2 style={{ fontSize: 28, fontWeight: 700, color: "var(--text-primary)" }}>Typical Workflow</h2>

              <ol style={{ marginTop: 32, display: "flex", flexDirection: "column", gap: 16, fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.65, listStyleType: "decimal", paddingLeft: 20 }}>
                <li><strong style={{ color: "var(--text-primary)", fontWeight: 600 }}>Sign in</strong> via GitHub or GitLab OAuth.</li>
                <li><strong style={{ color: "var(--text-primary)", fontWeight: 600 }}>Select a repository</strong> from your account and choose a branch.</li>
                <li><strong style={{ color: "var(--text-primary)", fontWeight: 600 }}>Run analysis</strong> — Refract scans every file, runs all detectors, and builds the import map.</li>
                <li><strong style={{ color: "var(--text-primary)", fontWeight: 600 }}>Review results</strong> on the Project View page.</li>
                <li><strong style={{ color: "var(--text-primary)", fontWeight: 600 }}>Accept or reject</strong> individual suggestions.</li>
                <li><strong style={{ color: "var(--text-primary)", fontWeight: 600 }}>Apply changes</strong> — Free users copy patches manually. Pro/Team users click "Generate PR".</li>
                <li><strong style={{ color: "var(--text-primary)", fontWeight: 600 }}>Generate documentation</strong> — One-click README, API docs, or architecture docs.</li>
              </ol>
            </section>

            {/* Safety & Trust */}
            <section id="safety" style={{ scrollMarginTop: 96, marginBottom: 80, borderTop: "1px solid var(--border-subtle)", paddingTop: 64 }}>
              <h2 style={{ fontSize: 28, fontWeight: 700, color: "var(--text-primary)" }}>Safety &amp; Trust</h2>

              <p style={{ marginTop: 16, fontSize: 16, color: "var(--text-secondary)", lineHeight: 1.65 }}>
                Refract is designed as a read-first, write-never-by-default system:
              </p>

              <ul style={{ marginTop: 24, display: "flex", flexDirection: "column", gap: 12, fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.65, listStyleType: "disc", paddingLeft: 20 }}>
                <li><strong style={{ color: "var(--text-primary)" }}>Analysis is read-only.</strong> The engine never modifies your repository without explicit user action.</li>
                <li><strong style={{ color: "var(--text-primary)" }}>Pull requests, not direct pushes.</strong> When applying changes, Refract creates a PR that you review and merge.</li>
                <li><strong style={{ color: "var(--text-primary)" }}>Suggestions are deterministic.</strong> Every detector produces the same result for the same input.</li>
                <li><strong style={{ color: "var(--text-primary)" }}>Sandboxed execution.</strong> Analysis runs in isolated Web Workers with no access to the DOM or network.</li>
              </ul>
            </section>

            {/* Privacy & Data */}
            <section id="privacy" style={{ scrollMarginTop: 96, marginBottom: 80, borderTop: "1px solid var(--border-subtle)", paddingTop: 64 }}>
              <h2 style={{ fontSize: 28, fontWeight: 700, color: "var(--text-primary)" }}>Privacy &amp; Data</h2>

              <ul style={{ marginTop: 32, display: "flex", flexDirection: "column", gap: 12, fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.65, listStyleType: "disc", paddingLeft: 20 }}>
                <li><strong style={{ color: "var(--text-primary)" }}>Your code stays on your machine.</strong> All parsing, analysis, and issue generation happens client-side.</li>
                <li><strong style={{ color: "var(--text-primary)" }}>Repository metadata only.</strong> Only repository metadata is fetched — file contents remain local during analysis.</li>
                <li><strong style={{ color: "var(--text-primary)" }}>No code logging.</strong> We never log, store, or transmit your source code.</li>
                <li><strong style={{ color: "var(--text-primary)" }}>AI features are opt-in.</strong> If using AI-assisted suggestion generation, context is sent with your explicit consent.</li>
              </ul>
            </section>

            {/* Best Practices */}
            <section id="best-practices" style={{ scrollMarginTop: 96, marginBottom: 80, borderTop: "1px solid var(--border-subtle)", paddingTop: 64 }}>
              <h2 style={{ fontSize: 28, fontWeight: 700, color: "var(--text-primary)" }}>Best Practices</h2>

              <ul style={{ marginTop: 32, display: "flex", flexDirection: "column", gap: 12, fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.65, listStyleType: "disc", paddingLeft: 20 }}>
                <li><strong style={{ color: "var(--text-primary)" }}>Run analysis early.</strong> Connect your repository as soon as you have a working prototype.</li>
                <li><strong style={{ color: "var(--text-primary)" }}>Focus on High priority issues first.</strong> The priority score accounts for both impact and blast radius.</li>
                <li><strong style={{ color: "var(--text-primary)" }}>Batch related suggestions.</strong> Accepting multiple suggestions in a single PR reduces review overhead.</li>
                <li><strong style={{ color: "var(--text-primary)" }}>Re-analyze after refactoring.</strong> Run a fresh analysis after applying changes to verify improvements.</li>
              </ul>
            </section>

            {/* FAQ */}
            <section id="faq" style={{ scrollMarginTop: 96, marginBottom: 80, borderTop: "1px solid var(--border-subtle)", paddingTop: 64 }}>
              <h2 style={{ fontSize: 28, fontWeight: 700, color: "var(--text-primary)" }}>FAQ</h2>

              <div style={{ marginTop: 40, display: "flex", flexDirection: "column", gap: 32 }}>
                {[
                  { q: "What is \"comprehension debt\"?", a: "Comprehension debt is the gap between code that works and code that is understood. AI-generated code is particularly prone to this because it optimizes for correctness over readability." },
                  { q: "Does Refract modify my code without permission?", a: "No. Analysis is always read-only. Any modification goes through a pull request workflow that you explicitly initiate and review." },
                  { q: "Can I use Refract with JavaScript projects?", a: "Yes. Refract supports TypeScript and JavaScript files (.ts, .tsx, .js, .jsx) via Babel's TypeScript plugin." },
                  { q: "How long does analysis take?", a: "Typical repositories (under 10,000 files) complete in under 5 minutes. Incremental re-analysis takes under 30 seconds." },
                  { q: "Does Refract work with monorepos?", a: "Yes. Refract treats the repository as a flat file system for import resolution. Monorepo structures with relative imports work correctly." },
                  { q: "Is Refract open source?", a: "Refract is proprietary software. A free tier is available for individual developers. Pro and Team plans unlock automated refactoring and team collaboration." },
                ].map((f) => (
                  <div key={f.q}>
                    <h3 style={{ fontSize: 18, fontWeight: 600, color: "var(--text-primary)" }}>{f.q}</h3>
                     <p style={{ marginTop: 8, fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.65 }}>{f.a}</p>
                  </div>
                ))}
              </div>
            </section>

            {/* Getting Started */}
            <section id="getting-started" style={{ scrollMarginTop: 96, borderTop: "1px solid var(--border-subtle)", paddingTop: 64 }}>
              <h2 style={{ fontSize: 28, fontWeight: 700, color: "var(--text-primary)" }}>Getting Started</h2>

              <div style={{ marginTop: 32 }}>
                <h3 style={{ fontSize: 18, fontWeight: 600, color: "var(--text-primary)" }}>Prerequisites</h3>
                <ul style={{ marginTop: 12, display: "flex", flexDirection: "column", gap: 8, fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.65, listStyleType: "disc", paddingLeft: 20 }}>
                  <li>A GitHub or GitLab account with repositories you want to analyze</li>
                  <li>A modern web browser (Chrome, Firefox, Safari, or Edge)</li>
                </ul>
              </div>

              <div style={{ marginTop: 32 }}>
                <h3 style={{ fontSize: 18, fontWeight: 600, color: "var(--text-primary)" }}>Quick Start</h3>
                <ol style={{ marginTop: 16, display: "flex", flexDirection: "column", gap: 12, fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.65, listStyleType: "decimal", paddingLeft: 20 }}>
                  <li><strong style={{ color: "var(--text-primary)" }}>Visit the app</strong> and sign in via GitHub or GitLab OAuth.</li>
                  <li><strong style={{ color: "var(--text-primary)" }}>Connect a repository</strong> from your account and choose a branch.</li>
                  <li><strong style={{ color: "var(--text-primary)" }}>Run your first analysis</strong> — starts automatically after connecting.</li>
                  <li><strong style={{ color: "var(--text-primary)" }}>Review your results</strong> — health score, issues, and suggestions.</li>
                  <li><strong style={{ color: "var(--text-primary)" }}>Accept a suggestion</strong> — click to see the before/after diff.</li>
                  <li><strong style={{ color: "var(--text-primary)" }}>Generate a PR (Pro/Team)</strong> — create a pull request with all accepted changes.</li>
                </ol>
              </div>
            </section>

          </div>
        </div>
      </div>

      <Footer />
    </main>
  );
};

export default Documentation;
