import { SIGNUP_PATH } from "@/lib/constants";
import type { FilmLine } from "@/lib/film";

export const homeSeo = {
  title: "Refract — AI wrote it. Make it ready to ship.",
  description:
    "Refract takes code generated by AI and turns it into cleaner, more organized software — before the mess becomes the project.",
  ogTitle: "AI wrote it. Make it ready to ship.",
  ogDescription:
    "The step after generate. Refract cleans and tightens AI-generated code so you can keep shipping.",
};

export const homeHero = {
  eyebrow: "The step after AI writes the code",
  headline: "AI wrote it. Make it ready to ship.",
  subhead:
    "Refract takes the code your AI tools produce and turns it into something cleaner, more consistent, and easier to keep — so the project doesn’t fall apart as it grows.",
  primary: { label: "Get started", href: SIGNUP_PATH },
  secondary: { label: "See how it works", href: "/product" },
  trust: "You approve every change. Refract never rewrites your project on its own.",
  caption: "Before it becomes the codebase",
};

export const homeShift = {
  headline: "Writing code stopped being the hard part.",
  paragraphs: [
    "A few years ago, the slow work was producing software. Now a developer with AI can fill a repository in an afternoon.",
    "The code often runs. That’s the trap.",
    "What used to take a week now lands as a first draft that looks finished. Screens fetch their own data. The same logic shows up in three files. State hangs around after nobody needs it. The project still compiles. Two months later, nobody wants to touch it.",
    "AI made writing faster. It did not make maintaining easier.",
  ],
};

export const homeProblem = {
  headline: "Working code can still be a mess.",
  paragraphs: [
    "AI is good at the next function. It is worse at the next six months.",
    "It writes what fits the prompt in front of it. It does not live with the project. So you get software that passes the demo and quietly gets harder to change:",
  ],
  bullets: [
    "the same behavior, copied instead of shared",
    "interface code doing work that doesn’t belong there",
    "leftover state and effects that only made sense in the moment",
    "structure that made sense for one file, not for a product",
  ],
  after: "None of this looks like a dramatic failure. It looks like a codebase you stop trusting.",
  close: "You don’t need more generated code. You need the generated code to stay good.",
};

export const homeGrowth = {
  headline: "Then the project grows. And the first drafts become the product.",
  paragraphs: [
    "One messy screen is a nuisance. Forty messy screens are a team that ships slower than before they had AI.",
    "New features take longer because nothing sits in the right place. Two people “fix” the same thing in different files. The AI keeps generating against a foundation that is already tangled — so every new piece fits a little worse.",
    "The feeling is not “we have bugs.” The feeling is “this used to be fast, and now I’m afraid to change it.”",
  ],
};

export const homeTurn = {
  headline: "Refract is what happens after the AI writes the code.",
  paragraphs: [
    "Keep using the tools that help you build. Refract is not a replacement for them.",
    "It reads the project, finds the patterns that make AI-generated code hard to live with, and turns them into cleaner, more organized software — with you deciding what lands.",
    "Not another list of complaints. A cleaner project.",
  ],
  cta: { label: "Get started", href: SIGNUP_PATH },
};

export const homeResult = {
  headline: "The result is code you can keep.",
  points: [
    {
      title: "Cleaner",
      body: "The obvious mess gets <strong>pulled out of the screens</strong> and put where it belongs.",
    },
    {
      title: "More consistent",
      body: "<strong>Repeated logic stops multiplying.</strong> The project starts to look like one product, not twelve first drafts.",
    },
    {
      title: "Easier to change",
      body: "You can <strong>add the next thing</strong> without stepping through a maze that nobody meant to build.",
    },
    {
      title: "Still yours",
      body: "<strong>Nothing changes until you say yes.</strong> You see what will happen. You keep the merge button.",
    },
  ],
};

export const homeDoes = {
  headline: "It doesn’t just point at problems. It makes the code better.",
  points: [
    {
      number: "1",
      title: "It learns the project first",
      body: "Refract looks at how the software is actually put together — not only the last file that changed — so a cleanup fits the project you already have.",
    },
    {
      number: "2",
      title: "It finds the mess AI tends to leave behind",
      body: "Copied logic. Data fetching inside the interface. State that nobody uses. Effects that linger. Structure that will hurt as soon as the app grows.",
    },
    {
      number: "3",
      title: "It tells you what to clean first",
      body: "When there’s more than one issue, you get an order that makes sense — not a wall of noise.",
    },
    {
      number: "4",
      title: "It can do the cleanup for you",
      body: "When the change is safe and contained, Refract prepares it. You approve. It applies the change and checks that the project still holds together. If it can’t do the change safely, it says so, instead of guessing.",
    },
  ],
};

export const homeWorld = {
  headline: "It shows up where the code is about to become the project.",
  paragraphs: [
    "Connect the repositories you care about. When new code is proposed, Refract reviews it in place.",
    "You get one clear result:",
  ],
  bullets: [
    "nothing important to clean, or",
    "a cleanup ready for you to approve, or",
    "something you should look at, explained in plain language",
  ],
  close:
    "Approve on GitHub. Stay in the flow you already have. Refract does not ask you to live in a second inbox.",
  caption: "One result. You decide.",
};

export const homeTrust = {
  headline: "Controlled. Visible. Reversible in practice — because you are still in charge.",
  points: [
    {
      title: "You approve.",
      body: "Refract never applies a change until you do.",
    },
    {
      title: "It would rather stay quiet than be wrong.",
      body: "If it can’t prove a problem, it doesn’t invent one to look busy.",
    },
    {
      title: "If it can’t clean something safely, it doesn’t pretend.",
      body: "You get an explanation, not a reckless rewrite.",
    },
    {
      title: "It checks its own work.",
      body: "After a cleanup lands, Refract looks again. A failed cleanup is never described as success.",
    },
    {
      title: "It is not a chatbot rewriting your app.",
      body: "The cleanups it applies are specific and constrained. Creative guesses are not “fixes.”",
    },
  ],
};

export const homeSteps = {
  headline: "Three steps. Then it runs while you work.",
  steps: [
    {
      number: "1",
      title: "Create an account",
      body: "Email and password. That’s your Refract login — not a GitHub sign-in.",
    },
    {
      number: "2",
      title: "Connect GitHub and pick repositories",
      body: "Install the Refract app on the projects you want cleaned. You choose which ones.",
    },
    {
      number: "3",
      title: "Keep shipping",
      body: "Open a pull request like you already do. Refract reads the change in the context of the project. If a cleanup is ready, you approve it. Then you merge when you’re ready.",
    },
  ],
  note: "Installing the app is not the same as signing in. Your Refract account and your GitHub access stay separate on purpose.",
  cta: { label: "Get started", href: SIGNUP_PATH },
};

export const homeAudience = {
  headline: "For people who build with AI and still have to live with the result.",
  points: [
    {
      title: "Individuals",
      body: "You’re shipping a product with Copilot, Cursor, or the next model. The code comes fast. You want it to stay something you can maintain.",
    },
    {
      title: "Teams",
      body: "Several people generating at once. The repo is the shared memory. Refract is how that memory stays coherent.",
    },
    {
      title: "Built for today",
      body: "React and TypeScript on GitHub. That’s where this problem is loudest right now. Other stacks come when they’re real — not as a promise on the homepage.",
    },
  ],
};

export const homeSocial = {
  headline: "Teams generating software need a step after generate.",
  line: "Used by developers who build with AI on GitHub.",
  invite: "Want to be an early team?",
  inviteHref: "/contact",
  inviteLabel: "Contact us",
};

export const homeHonesty = {
  headline: "What Refract is not.",
  paragraphs: [
    "It is not an IDE. It is not a replacement for your AI coding tools. It is not a generic linter. It is not a bot that leaves twenty comments on every line.",
    "It will not reorganize your entire product overnight. It will not auto-fix every security issue. It will not merge for you.",
    "It will make the AI-generated parts of a React and TypeScript project cleaner, clearer, and easier to keep — with you in control.",
  ],
};

export const homeCta = {
  headline: "Generate the code. Don’t inherit the mess.",
  body: "Create an account, connect GitHub, and let Refract take the first drafts the rest of the way.",
  primary: { label: "Get started", href: SIGNUP_PATH },
  secondary: { label: "See pricing", href: "/pricing" },
};

export const heroFilm: { file: string; lines: FilmLine[] } = {
  file: "src/screens/Orders.tsx",
  lines: [
    { state: "kept", text: "export function Orders() {" },
    { state: "added", text: "  const { data, loading } = useOrders()" },
    { state: "removed", text: "  const [data, setData] = useState([])" },
    { state: "removed", text: "  const [loading, setLoading] = useState(true)" },
    { state: "removed", text: "" },
    { state: "removed", text: "  useEffect(() => {" },
    { state: "removed", text: "    fetch('/api/orders')" },
    { state: "removed", text: "      .then((r) => r.json())" },
    { state: "removed", text: "      .then(setData)" },
    { state: "removed", text: "      .finally(() => setLoading(false))" },
    { state: "removed", text: "  }, [])" },
    { state: "removed", text: "" },
    { state: "kept", text: "  return <List items={data} loading={loading} />" },
    { state: "kept", text: "}" },
  ],
};
